[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
case_iterable = "0.2.0"
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
nalgebra = "0.34"
simplelog = "0.12"
